# Generated by Django 4.2.2 on 2023-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[(1, 'premium'), (2, 'basic')], default=2, max_length=200),
        ),
    ]
