# Generated by Django 4.2.2 on 2023-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
