# Generated by Django 4.2.2 on 2023-07-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('google_store_url', models.CharField(max_length=255)),
                ('bazar_url', models.CharField(max_length=255)),
                ('miket_url', models.CharField(max_length=255)),
                ('importance', models.IntegerField(choices=[(1, 'update'), (2, 'not important')], default=1)),
            ],
        ),
    ]
