# Generated by Django 4.2.2 on 2023-06-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.IntegerField(default=1)),
                ('upload_file', models.FileField(upload_to='media')),
                ('file_type', models.PositiveSmallIntegerField(choices=[(1, 'image'), (2, 'font'), (3, 'dynamic')])),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
