# Generated by Django 4.2.2 on 2023-06-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'image'), (2, 'font'), (3, 'dynamic')], default=1),
        ),
    ]
