# Generated by Django 4.2.2 on 2023-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_type',
            field=models.CharField(choices=[(1, 'image'), (2, 'font'), (3, 'dynamic')], default=1, max_length=200),
        ),
    ]
