# Generated by Django 4.2.2 on 2023-07-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='upload_file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
