# Generated by Django 4.2.2 on 2023-07-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_asset_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='preview',
            field=models.ImageField(null=True, upload_to='media/asset'),
        ),
    ]
