# Generated by Django 4.2.2 on 2023-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_asset_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='preview',
            field=models.ImageField(null=True, upload_to='asset'),
        ),
    ]
