# Generated by Django 4.2.2 on 2023-07-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(1, 'visible'), (2, 'hidden')], default=2),
        ),
    ]
